### ISSUE TITLE
Update procedure has some errors and we need the new IP

### ISSUE THREAD

**Issue by RaulBernal** [Lunes-platform/LunesNode#8]
https://github.com/Lunes-platform/LunesNode/wiki/Network-updating-procedures

- To fix:
points 3, 9, 10 change the params order, in example: 
change `sudo service stop lunesnode`  by `sudo service  lunesnode stop`  
The same for start and status.

- To add: 
`the new IP addressed will be released for public update.`  Really we need this IP. 

I think a network upgrade must be consensed with node operators. Dev could make a Telegram/Discord group (there is an existent one) to agree with us the changes, params, timetables (because we are word wide)

**Comment by RaulBernal** [comment]
Another good resource we can share is a snapshoot of the chain before a upgrade. 
I think we must agree a block-height to stop and upgrade, not a date period,

**Comment by olivmath** [comment]
Hello, we are looking to continue in an objective and collaborative way [here](https://t.me/joinchat/QqjFksU3wQYxMjBl)
#golunes
